<a href="https://colab.research.google.com/github/souma20713/DeepLearning2022Late/blob/main/NumPyReplay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as  np

In [4]:
import numpy as  np
x = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
print(x)

[1. 2. 3. 4. 5.]


In [5]:
x = np.array([1,2,3])
print(x) # [1 2 3]
print(type(x)) 

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
my_list1 = [1,2,3,4,5]
my_array1 = np.array(my_list1)

In [7]:
my_list2 = [10,20,30,40,50]
my_lists = [my_list1, my_list2] 
my_lists # [[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]]

[[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]]

In [8]:
my_array2 = np.array(my_lists)

In [10]:
my_array2
"""
array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])
"""

'\narray([[ 1,  2,  3,  4,  5],\n       [10, 20, 30, 40, 50]])\n'

In [13]:
#np.array((1,2,3),(4,5,6))

In [14]:
import numpy as np
a = np.array([1, 2, 3, 4])


In [15]:
a.shape

(4,)

In [16]:
b = np.array([[1, 2],[3,4]])

In [17]:
b.shape

(2, 2)

In [18]:
import numpy as  np
x = np.arange(10)
print(x)
x = np.arange(1, 10).reshape(3,3) 
y = np.arange(1, 10).reshape(3,3)
"""
x = np.reshape(x, (3,3))
"""
print(x)
print(y)

print(x + y)
print(x - y)
print(x * y)



[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [19]:
import numpy as np
sample_array = np.arange(10)
print(sample_array)
sample_array2 = sample_array.reshape(2,5)
print(sample_array2)
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
print(np.concatenate([sample_array3,sample_array4],axis=1))
print(np.hstack((sample_array3,sample_array4)))
print(np.concatenate([sample_array3,sample_array4],axis=0))
print(np.vstack((sample_array3,sample_array4)))


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
import numpy as np

In [21]:
sample_array = np.arange(10)
print(sample_array)

print(sample_array + 5)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [22]:
import numpy as np

n1 = np.array([1,2,3,4,5])
print(n1) # [1 2 3 4 5]


[1 2 3 4 5]


In [23]:
np.ndim(n1)

1

In [24]:
n1.shape

(5,)

In [25]:
n2 = np.array([[1,2], [3,4], [5,6]])
print(n2)

[[1 2]
 [3 4]
 [5 6]]


In [26]:
print(n2.ndim)

2


In [27]:
import numpy as np
my_li1 = [-1,4]

my_li2 = [3,2]

my_li3 = [2,5]

my_li4 = [0,1]

my_lists = [my_li1,my_li2,my_li3,my_li4]

my_array3 = np.array(my_lists)

my_array3
"""
array([[-1,  4],
       [ 3,  2],
       [ 2,  5],
       [ 0,  1]])
"""

'\narray([[-1,  4],\n       [ 3,  2],\n       [ 2,  5],\n       [ 0,  1]])\n'